[package]
name = "tokio-tun"
version = "0.2.2"
authors = ["Navid <yaa110@gmail.com>"]
edition = "2018"
homepage = "https://github.com/yaa110/tokio-tun"
repository = "https://github.com/yaa110/tokio-tun"
documentation = "https://docs.rs/tokio-tun"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Asynchronous allocation of TUN/TAP devices using tokio"
categories = ["asynchronous", "network-programming"]
keywords = ["tun", "tap", "async", "mio", "tokio"]

[dependencies]
tokio = { version = "0.2.22", features = ["io-driver"] }
libc = "0.2"
nix = "0.18"
mio = "0.6.22"

[dev-dependencies]
tokio = { version = "0.2", features = ["io-util", "rt-threaded", "macros"] }

[build-dependencies]
bindgen = "0.55"
