[package]
name = "tokio-tun"
version = "0.3.0"
authors = ["Navid <yaa110@gmail.com>"]
edition = "2018"
homepage = "https://github.com/yaa110/tokio-tun"
repository = "https://github.com/yaa110/tokio-tun"
documentation = "https://docs.rs/tokio-tun"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Asynchronous allocation of TUN/TAP devices using tokio"
categories = ["asynchronous", "network-programming"]
keywords = ["tun", "tap", "async", "mio", "tokio"]

[dependencies]
tokio = { version = "1.0", features = ["fs"] }
libc = "0.2"
nix = "0.19"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
bindgen = "0.56"
